server:
  port: 8080

# Database configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/file_upload
    username: itutorix
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
